GET http://newsapi.org/v2/everything?q=coronavirus&from=2020-03&sortBy=publishedAt&apiKey=dd118ea81ac5402b932473468a0b8cdb

###

GET http://localhost/api/storeTime.php

POST http://localhost:3000/api/storeTime.php

{
  "timestamp": 1586109979
}
